services:
  app:
    container_name: exceptions-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
networks:
  lion:
    driver: bridge
